### ISSUE TITLE
Automatic search of free channels

### ISSUE THREAD

**Issue by brat002** [openLRSng/openLRSng#114]
Could you implement automatic search of free channels on every binding of receiver/transmitter? This thing can be optional.

**Comment by jimmycapizzi** [comment]
+1

**Comment by DoctorAudio** [comment]
+1

**Comment by geofrancis** [comment]
a better way to do it would be to scan the band on startup before choosing free channels

**Comment by csurf** [comment]
scan on startup would require re-binding with the RX every time, as the hop channel sequence is part of the configuration data that is exchanged with the RX when binding occurs. Otherwise, the RX wouldn't know what hop channel sequence the TX will be using.

@mikeller 
kha already implemented the auto channel scan feature a while back, so we can probably close this out...
