### ISSUE TITLE
Mavlink Protocol

### ISSUE THREAD

**Issue by lucafedechen** [openLRSng/openLRSng#54]
Hi.
the openlrsng telemetry it's suitable at the moment for handle the mavlink protocol in telemetry mode??
congratulation for this project
thank you
regards

**Comment by adriano65** [comment]
Hi Kha,
i'd like to have mavlink on openlrs-ng side of my bixler2.
Currently i use clear serial channel at 9600 baud and with some opentx
modifications i could see 30-40% of packets lost in field.
It is ok for me since i use mavlink only to verify GPS lock.
But my final goal is to log GPS fixes on my radios (sky9x and 9xrpro)
and be able to have last position of my plane in case of failure.
Obviously i have 1W hawkeye receiver.
When you'll gain some time on this feature, i'll be happy to help.

**Comment by ilihack** [comment]
Yess, i am very too for the BIG openlrsng 4.0 Update for Mavlink ;-)

**Comment by kh4** [comment]
There will be 3.9 soonish, which will raise the telemetry data limits quite a bit, it will not contain any mavlink specifics though. Mavlink may then come to 3.10 or 4.0 depending a bit if I manage to lose arduino dependencies or not (32u4 USB support is the key here).

**Comment by adriano65** [comment]
Thank you, Kari.
I'll be great to lose arduino deps, i helped a little in opentx project
and it can be a nice source of info about USB (even if it is on ARM only)
Nice Day!

**Comment by artemen** [comment]
Kha, can you introduce asymmetrical serial baud rate? i.e. since Rx has uplink bandwidth fully available and similarly Tx has downlink fully available as well.

**Comment by kh4** [comment]
What you mean 
- baudrate X on transmitter and baudrate Y on the receiver
 -this should be possible already now
or
- baudrate X on transmitter.RX/receiver.TX and Y on transmitter.TX/receiver.RX
  - this cannot be done due to hardware limitation

**Comment by artemen** [comment]
There is a a version of softserial by APM guys which is written
specifically for atmega with respect to timing and interrupts. It is quite
a bit smaller as well. Not insisting, just for information purpose. It
stops serial transmission mid cycle to allow time sensitive  data such as
ppm/ pwm/ PIDs.

**Comment by DavidDavidov** [comment]
Any update on the Mavlink telemetry?

Can we try to merge the gitsly branch?
How stable link provide gitsly code?

**Comment by csurf** [comment]
moved to #152, closing...
