### ISSUE TITLE
Swap GPIOs and RFM23BP

### ISSUE THREAD

**Issue by Timvrakas** [openLRSng/openLRSng#70]
Hello! I'm working custom on a bi-directional 1w radio set. I'm confused about the SWAP_GPIOS define, and about what constitutes regular and what constitutes swapped gpio. 

Also after smoking my first prototype I caught wind that the logic on the 23bp is 3.3v while the VCC is 5-6v. Is this true?

My prototype has identical pin out to the OpenLRSminiRX, but uses the rfm22. Can I use HW type 5 and compile for RX? Or are there rfm23bp related changes that need to be made?

Thanks and awesome project!!

EDIT: I think I need SWAP_GPIOS, I have RXANT coneccted to GPIO0, TXANT to GPIO1 on an RFM23BP. If you want you can look at the schematics, they are in my repo "OpenLRS-APM"

**Comment by stormjohn** [comment]
Hi guys. How common is this GPIO issue? I have a Flyton M3 (1W) and its only producing just over 100mW on my power meter with a "dummy load" no matter what I try (compile 3.8).
Regards Lyn

**Comment by linuxslate** [comment]
I am still confused about this.  I am also building a DIY 1W XMTR with a RFM23BP.

I have GPIO0 connected to RX ON, and GPIO1 connected to TX ON.  In other words, they are NOT Crossed.  It is wired like I see everyone wiring RFM22B's

There for I thought I did NOT need #define SWAP_GPIOS.

But then I looked at the code.  In common.h, I see:

```
#ifdef SWAP_GPIOS
  spiWriteRegister(0x0b, 0x15);    // gpio0 RX State
  spiWriteRegister(0x0c, 0x12);    // gpio1 TX State
#else
  spiWriteRegister(0x0b, 0x12);    // gpio0 TX State
  spiWriteRegister(0x0c, 0x15);    // gpio1 RX State
```
This seems to indicate that if GPIO0 connected to RX ON, then I DO need SWAP_GPIO's.

Is the comment wrong?

Is 0x12 on or off?  I have read the RFM23BP data sheet, and I still don't get it.  Also, RX ON and TX ON are apparently active low.

Please help, as I have been messing with these both in software and hardware, and probably fried my module, but I cannot install another one with out understanding this.

If this "feature" can damage hardware, it should have never been added (especially with out better, clearer documentation).  Miss-wired hardware is a hardware problem, and should be fixed with a soldering iron, not code.

**Comment by mikeller** [comment]
> If this "feature" can damage hardware, it should have never been added (especially with out better, clearer documentation). Miss-wired hardware is a hardware problem, and should be fixed with a soldering iron, not code.

I don't think that this define was added with home-brew modules in mind (why wouldn't you just wire the pins as per data sheet there), but to cope with already existing modules that have the traces swapped on the PCB...
